#!/usr/bin/env ruby

require_relative "termplot-cmdline"
require_relative "termplot-screen"

# Extract options from the command line.
options = TermplotCmdline.parse ARGV

numSteps = options.cols - 1                   # Number of steps over x.
dx = (options.right - options.left)/numSteps  # Size of each step over x.
yMax = -1.0E+30                               # Maximum y value.
yMin =  1.0E+30                               # Minimum y value.
yVal = []                                     # y values.

# Take steps across x, and calculate y values.
(0..numSteps).each do |col|
   x = options.left + col*dx
   y = eval(options.expr)
   yMin = y if y < yMin
   yMax = y if y > yMax
   yVal[col] = y
end

screen = TermplotScreen.new(numCols: options.cols, numRows: options.rows)
(0..numSteps).each do |col|
   row = ((yVal[col] - yMin) / (yMax - yMin) * (options.rows - 1) + 0.5).to_i
   puts "#{col} #{row}"
   screen.set(col: col, row: row)
end

screen.print

